# Generated by Django 4.1.4 on 2023-01-03 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mayflower', '0007_cakedb_delete_auther_delete_bookdb'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='cakedb',
            new_name='icedb',
        ),
        migrations.RenameField(
            model_name='icedb',
            old_name='Cakename',
            new_name='Icecreamname',
        ),
    ]
